### ISSUE TITLE
Add unit test automation 

### ISSUE THREAD

**Issue by NovikovEvgeny** [NovikovEvgeny/mongodb-simplecrawler-queue#4]
Now tests are only integration tests - they require running and accessible mongodb

Would be cool to have unit tests for MongoQueue and utilities classes

**Comment by thuwie** [comment]
@NovikovEvgeny count me in

**Comment by NovikovEvgeny** [comment]
seems we still can increase test coverage with unit tests, so reopen

**Comment by NovikovEvgeny** [comment]
Unit tests for Mongo Queue added. Except for GC and Monitoring utils (will be covered as part of #9)
